name: Yarock
markdown: redcarpet
baseurl: /yarock
production_url : http://seb-apps.github.io/yarock
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
source: yarock

